version: '3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.windapp.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.services.windapp.loadbalancer.server.port=4000"

networks:
  web-network:
    driver: bridge 